# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_connexion.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 395)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.label_ID = QtWidgets.QLabel(Form)
        self.label_ID.setGeometry(QtCore.QRect(180, 20, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.lineEdit_identifiant = QtWidgets.QLineEdit(Form)
        self.lineEdit_identifiant.setGeometry(QtCore.QRect(310, 40, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_identifiant.setFont(font)
        self.lineEdit_identifiant.setObjectName("lineEdit_identifiant")
        self.label_MotdePasse = QtWidgets.QLabel(Form)
        self.label_MotdePasse.setGeometry(QtCore.QRect(160, 90, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_MotdePasse.setFont(font)
        self.label_MotdePasse.setObjectName("label_MotdePasse")
        self.lineEdit_motDePasse = QtWidgets.QLineEdit(Form)
        self.lineEdit_motDePasse.setGeometry(QtCore.QRect(310, 100, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_motDePasse.setFont(font)
        self.lineEdit_motDePasse.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_motDePasse.setObjectName("lineEdit_motDePasse")
        self.label_email = QtWidgets.QLabel(Form)
        self.label_email.setGeometry(QtCore.QRect(160, 150, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(310, 150, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.bouton_valider = QtWidgets.QPushButton(Form)
        self.bouton_valider.setGeometry(QtCore.QRect(250, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bouton_valider.setFont(font)
        self.bouton_valider.setObjectName("bouton_valider")
        self.label_message = QtWidgets.QLabel(Form)
        self.label_message.setGeometry(QtCore.QRect(30, 250, 511, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_message.setFont(font)
        self.label_message.setText("")
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setWordWrap(True)
        self.label_message.setObjectName("label_message")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_ID.setText(_translate("Form", "Identifiant :"))
        self.label_MotdePasse.setText(_translate("Form", "Mot de passe :"))
        self.label_email.setText(_translate("Form", "Adresse mail :"))
        self.bouton_valider.setText(_translate("Form", "Valider"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
